name: 1.0$(Rev:.r)

trigger:
- main

pool:
  vmImage: 'windows-2022'

variables:
  vsix: '$(Build.ArtifactStagingDirectory)/vsix/agent-screenshot-$(Build.BuildNumber).vsix'

steps:
- task: replacetokens@5
  inputs:
    targetFiles: '**/*.json'
    encoding: 'utf-8'
    writeBOM: false
    actionOnMissing: 'continue'
    keepToken: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'
    useLegacyPattern: false
    enableTelemetry: true

- task: TfxInstaller@4
  inputs:
    version: 'v0.x'

- task: PackageAzureDevOpsExtension@4
  inputs:
    rootFolder: '$(Build.SourcesDirectory)'
    outputPath: '$(vsix)'
    extensionVersion: '$(Build.BuildNumber)'
    updateTasksVersion: true
    extensionVisibility: 'public_preview'

- task: PublishAzureDevOpsExtension@4
  inputs:
    connectTo: 'VsTeam'
    connectedServiceName: 'Jesse Houwing'
    fileType: 'vsix'
    vsixFile: '$(vsix)'
    noWaitValidation: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'Output'

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'GitHub - jessehouwing'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: '$(Build.BuildNumber)'
    title: '$(Build.BuildNumber)'
    releaseNotesSource: 'inline'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
