name: 1.0$(Rev:.r)

trigger:
- main

pool:
  vmImage: 'windows-2022'

variables:
  vsix: '$(Build.ArtifactStagingDirectory)/vsix/agent-screenshot-$(Build.BuildNumber).vsix'
  marketplaceServiceConnection: '24325a98-0d4b-4180-9936-c930a4156258' 

steps:
- task: replacetokens@6
  inputs:
    sources: '**/*.json'
    encoding: 'utf-8'
    addBOM: false

- task: TfxInstaller@4
  inputs:
    version: 'v0.x'

- task: PackageAzureDevOpsExtension@4
  inputs:
    rootFolder: '$(Build.SourcesDirectory)'
    outputPath: '$(vsix)'
    extensionVersion: '$(Build.BuildNumber)'
    updateTasksVersion: true
    extensionVisibility: 'public_preview'

- task: AzureCLI@2
  displayName: 'Authenticate with Service Principal'
  inputs:
    azureSubscription: 'azure-devops-marketplace'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    useGlobalConfig: true
    inlineScript: |
      $accessToken = az account get-access-token --resource 499b84ac-1321-427f-aa17-267ca6975798 --query "accessToken" --output tsv
      write-host "##vso[task.setsecret]$accessToken"
      write-host "##vso[task.setendpoint id=$env:MARKETPLACESERVICECONNECTION;field=authParameter;key=password]$accessToken"

- task: PublishAzureDevOpsExtension@4
  inputs:
    connectTo: 'VsTeam'
    connectedServiceName: $(marketplaceServiceConnection)
    fileType: 'vsix'
    vsixFile: '$(vsix)'
    noWaitValidation: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'Output'

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'GitHub - jessehouwing'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: '$(Build.BuildNumber)'
    title: '$(Build.BuildNumber)'
    releaseNotesSource: 'inline'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
